all:
  children:
    cisco:
      children:
        ciscoIOS:
          hosts:
            CSR1:
              ansible_host: 192.168.29.201
              ansible_network_os: cisco.ios.ios
            CSR2:
              ansible_host: 192.168.29.202
              ansible_network_os: cisco.ios.ios
            C8K1:
              ansible_host: 192.168.29.200
              ansible_network_os: cisco.ios.ios
        ciscoNXOS:
          hosts:
            NXOS1:
              ansible_host: 192.168.29.203
              ansible_network_os: cisco.nxos.nxos
            NXOS2:
              ansible_host: 192.168.29.204
              ansible_network_os: cisco.nxos.nxos
        ciscoVIOS:
          hosts:
            VIOS1:
              ansible_host: 192.168.29.205
              ansible_network_os: cisco.ios.ios
    arista:
      children:
        aristaEOS:
          hosts:
            EOS1:
              ansible_host: 192.168.29.206
              ansible_network_os: arista.eos.eos
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_become: true
    ansible_become_method: enable
    ansible_user: nw_automation
    ansible_password: devnet