---
- name: Demo on ios_commands
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: Demo on prompt
      cisco.ios.ios_command:
        commands:
          - command: 'clear counters GigabitEthernet2'
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: 'y'
      register: clear_counter_output

    - name: Display clear_counter_output
      ansible.builtin.debug:
        var: clear_counter_output