---
- name: Demo on ios_config
  hosts: ciscoIOS
  gather_facts: false
  tasks:
    - name: Configure hostname
      cisco.ios.ios_config:
        lines: 
          - hostname {{ inventory_hostname }}
          - ip name-server {{ dns_server }}
          - ntp server {{ ntp_server }}
          - ip domain name {{ domain_name }}
      register: output

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ output }}"