---
- name: Demo on ios_config
  hosts: ciscoIOS
  gather_facts: false
  tasks:
    - name: Configure Multiple Interfaces
      cisco.ios.ios_config:
        lines:
          - ip helper-address {{ dhcp_server_1 }}
          - ip helper-address {{ dhcp_server_2 }}
        parents: "{{ item }}"
      loop:
        - interface GigabitEthernet2
        - interface GigabitEthernet3
        - interface GigabitEthernet4
      register: output

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ output }}"