---
- name: Demo on ios_config
  hosts: ciscoIOS
  gather_facts: false
  tasks:
    - name: Configure Multiple Interfaces
      cisco.ios.ios_config:
        lines:
          - description {{ item.description }}
          - ip address {{ item.ip_address }} {{ item.mask }}
        parents:
          - interface {{ item.name }}
      loop: "{{ interface_details }}"
      register: output

    - name: Display output
      ansible.builtin.debug:
        msg: "{{ output }}"