---
- name: Demo on ios_config
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: Demo on diff_against
      cisco.ios.ios_config:
        lines:
          - description Connected to Management Interface
        parents:
          - interface GigabitEthernet1
        # backup: yes
        # backup_options:
        #   dir_path: "{{ playbook_dir }}/intended_config"
        #   filename: "{{ inventory_hostname }}_golden_config.txt"
        diff_against: intended
        intended_config: "{{ lookup('file', '{{ playbook_dir }}/intended_config/{{ inventory_hostname }}_golden_config.txt') }}"
        diff_ignore_lines:
          - clock *
      register: output
    
    - name: Display output
      ansible.builtin.debug:
        msg: "{{ output }}"