---
- name: Demo on ios_config
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: Demo on save_when
      cisco.ios.ios_config:
        lines:
          - description Connected to Management Interface
        parents:
          - interface GigabitEthernet1
        save_when: changed