---
- name: Demo on ServiceNow snow_record
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: Check Interface Status
      cisco.ios.ios_command:
        commands:
          - show ip interface brief | include GigabitEthernet4
      register: show_interface_status

    - name: Create ServiceNow Incident
      servicenow.servicenow.snow_record:
        # username: "{{ snow_username }}"
        # password: "{{ snow_password }}"
        # instance: "{{ snow_instance }}"
        username: admin
        password: CkH3Mbpr-3-V
        instance: dev265418
        state: present
        data:
          short_description: "GigabitEthernet4 Interface on {{ ansible_play_hosts[0] }} is currently down"
          description: |
            GigabitEthernet4 Interface on {{ ansible_play_hosts[0] }} is currently down.
            Please investigate and resolve the issue on priority.
          severity: 3
          priority: 2
      when: "'up' not in show_interface_status.stdout[0]"
      register: snow_output

    - name: Display snow_output
      ansible.builtin.debug:
        var: snow_output
    