---
- name: Pre-check commands
  cisco.ios.ios_command:
    commands:
      - "{{ item }}"
  loop: "{{ precheck_cmds }}"
  register: output

- name: Copy the content
  ansible.builtin.copy:
    content: "{{ output.results | to_nice_json }}"
    dest: "/home/nw_automation/ansible_course/13_Reusable_Automation_with_Collections_Roles_Includes_and_Imports/temp_files/prechecks_output.json"
  delegate_to: localhost