---
- name: Run show commands on Cisco IOS devices
  hosts: ciscoIOS
  gather_facts: false
  tasks:
    - name: Run show version command
      cisco.ios.ios_command:
        commands:
          - show version
      register: cisco_ios_command

    - name: Display cisco_ios_command output
      ansible.builtin.debug:
        msg:
          - "{{ (cisco_ios_command.stdout[0] | regex_findall('Cisco IOS XE Software, Version (\\S+)'))[0] }}"