---
- name: Gather Ansible Facts
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Display Ansible Facts
      ansible.builtin.debug:
        msg: 
         - "{{ ansible_facts }}"
         - "{{ ansible_facts.all_ipv4_addresses }}"
         - "{{ ansible_facts['all_ipv4_addresses'] }}"
         - "{{ ansible_all_ipv4_addresses }}"