---
- name: Demo on RegEx
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: Gather output of show command
      cisco.ios.ios_command:
        commands:
          - show version
          - show ip interface brief
      register: output

    - name: Apply RegEx
      ansible.builtin.debug:
        msg:
          - "{{ output.stdout[0] | regex_search('Cisco IOS XE Software, Version (\\S+)', '\\1') }}"
          - "{{ output.stdout[1] | regex_search('(\\S+)\\s+(\\d{1,3}.\\d{1,3}.\\d{1,3}.\\d{1,3})', '\\1', '\\2') }}"
          - "{{ output.stdout[1] | regex_findall('(\\S+)\\s+(\\d{1,3}.\\d{1,3}.\\d{1,3}.\\d{1,3})', '\\1', '\\2') }}"