---
- name: Demo on Textfsm
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: show command
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: show_command

    - name: TextFSM CLI Parser
      ansible.utils.cli_parse:
        # command: show ip interface brief
        text: "{{ show_command.stdout[0] }}"
        parser:
          name: ansible.utils.textfsm
          template_path: "{{ playbook_dir }}/templates/fetch_show_ip_interface_br.textfsm"
        set_fact: output
      
    - name: Display output
      ansible.builtin.debug:
        msg: "{{ output }}"
