---
- name: Demo on NTC Templates
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: show command
      cisco.ios.ios_command:
        commands:
          - show version
      register: show_command

    - name: NTC Templates CLI Parser
      ansible.utils.cli_parse:
        # command: show ip interface brief
        text: "{{ show_command.stdout[0] }}"
        parser:
          command: show version
          name: ansible.netcommon.ntc_templates
        set_fact: output
      
    - name: Display output
      ansible.builtin.debug:
        msg: "{{ output }}"
