---
- name: Demo on Ansible zip filter
  hosts: localhost
  gather_facts: false
  vars:
    device_names:
      - CSR1
      - CSR2
      - C8K1
    mgmt_addresses:
      - 192.168.29.201
      - 192.168.29.202
      - 192.168.29.200
    interfaces:
      - GigabitEthernet2
      - GigabitEthernet3
      - GigabitEthernet4
    ip_addresses:
      - 20.1.1.1
      - 20.1.2.1
      - 20.1.3.1
    mask:
      - 255.255.255.252
      - 255.255.255.0

  tasks:
    - name: Display original lists for reference
      ansible.builtin.debug:
        msg:
          - "Device Names: {{ device_names }}"
          - "IP Addresses: {{ mgmt_addresses }}"

    - name: Pair device names with IP addresses using zip filter
      ansible.builtin.debug:
        msg: "{{ device_names | zip(mgmt_addresses) | list }}"

    - name: Zip the interfaces with ip_addresses and mask
      ansible.builtin.debug:
        msg: "{{ interfaces | zip(ip_addresses, mask) | list }}"

    - name: Zip the interfaces with ip_addresses and mask using zip longest
      ansible.builtin.debug:
        msg: "{{ interfaces | zip_longest(ip_addresses, mask) | list }}"
    
    - name: Zip the interfaces with ip_addresses and mask using zip longest and fill_values
      ansible.builtin.debug:
        msg: "{{ interfaces | zip_longest(ip_addresses, mask, fillvalue='255.255.2555.0') | list }}"