---
- name: Demo on Jinja2 template
  hosts: ciscoIOS
  gather_facts: false
  tasks:
    - name: Generate basic configuration
      ansible.builtin.template:
        src: device_basic_config.j2
        dest: "{{ playbook_dir }}/config_files/{{ inventory_hostname }}_basic_config.cfg"