---
- name: Demo on check_mode
  hosts: CSR1
  gather_facts: false
  tasks: 
    - name: Configure description
      cisco.ios.ios_config:
        lines:
          - description Configured using check_mode
        parents:
          - interface GigabitEthernet4
      register: output
      check_mode: true

    - name: Display output
      ansible.builtin.debug:
        var: output

    - name: Configure DNS
      cisco.ios.ios_config:
        lines:
          - ip name-server 9.9.9.9
      check_mode: false
