---
- name: Demo on Ansible Lint
  hosts: CSR1
  gather_facts: false
  tasks:
    - name: Configure description
      cisco.ios.ios_config:
        lines:
          - description Testing Ansible Lint
        parents:
          - interface GigabitEthernet4
      register: output

    - name: Display output
      ansible.builtin.debug:
        var: output
