---
- name: Demo Playbook
  hosts: VIOS1
  gather_facts: false
  tasks:
    - name: Configured description
      cisco.ios.ios_config:
        lines:
          - description Management Interface
        parents:
          - interface GigabitEthernet0/0
      register: output

    - name: Display output
      ansible.builtin.debug:
        var: output